In [1]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../data/raw")

for file in DATA_DIR.glob("*.xlsx"):
    print("\nFILE:", file.name)

    excel = pd.ExcelFile(file)

    print("Sheets:")
    for sheet in excel.sheet_names:
        df = pd.read_excel(file, sheet_name=sheet)
        print(f"  {sheet}: {df.shape}")

FILE: Academic_Project_Similarity_Synthetic_Dataset.xlsx
Sheets:
  Projects: (600, 16)
  SimilarityPairs: (3000, 8)
  DataDictionary: (18, 3)
  README: (6, 2)

FILE: Project_Similarity_Pairs_0_to_4.xlsx
Sheets:
  Similarity_0: (1336, 8)
  Similarity_1: (334, 8)
  Similarity_2: (514, 8)
  Similarity_3: (581, 8)
  Similarity_4: (235, 8)

In [2]:
DATA_DIR = Path("../data/raw")

file = DATA_DIR / "Academic_Project_Similarity_Synthetic_Dataset.xlsx"

projects = pd.read_excel(
    file,
    sheet_name="Projects"
)

pairs = pd.read_excel(
    file,
    sheet_name="SimilarityPairs"
)

dictionary = pd.read_excel(
    file,
    sheet_name="DataDictionary"
)

print("PROJECTS")
print(projects.columns.tolist())

print("\nSIMILARITY PAIRS")
print(pairs.columns.tolist())

print("\nDATA DICTIONARY")
display(dictionary)

PROJECTS
['project_id', 'academic_year', 'department', 'program_level', 'project_status', 'domain', 'project_title', 'abstract', 'problem_statement', 'objectives', 'proposed_methodology', 'dataset', 'algorithm_model', 'technology_tools', 'keywords', 'data_source']

SIMILARITY PAIRS
['pair_id', 'project_A_id', 'project_B_id', 'same_semantic_family', 'baseline_lexical_overlap_proxy', 'expert_similarity_label', 'similarity_category', 'annotation_note']

DATA DICTIONARY

,field,description,sheet
0,project_id,Unique project identifier,Projects
1,academic_year,Academic year of project,Projects
2,department,Department/program unit,Projects
3,program_level,UG Mini Project / UG Mega Project / PG Dissert...,Projects
4,project_status,Completed or Ongoing,Projects
5,domain,Broad project domain,Projects
6,project_title,Project title,Projects
7,abstract,Project abstract,Projects
8,problem_statement,Problem being addressed,Projects
9,objectives,Project objectives,Projects
10,proposed_methodology,Proposed technical approach,Projects
11,dataset,Dataset or data source,Projects
12,algorithm_model,Main algorithm/model,Projects
13,technology_tools,Technology/tool stack,Projects
14,keywords,Domain keywords,Projects
15,data_source,REAL or SYNTHETIC,Projects
16,expert_similarity_label,0–4 similarity ground-truth label,SimilarityPairs
17,similarity_category,Human-readable similarity category,SimilarityPairs

In [3]:
display(projects.head(3))

,project_id,academic_year,department,program_level,project_status,domain,project_title,abstract,problem_statement,objectives,proposed_methodology,dataset,algorithm_model,technology_tools,keywords,data_source
0,SYN-0001,2022-23,MCA,UG Mini Project,Completed,Artificial Intelligence & Machine Learning,Prototype Crop Disease Detection Using CNN,This project proposes a ug mini project soluti...,Existing approaches to crop disease detection ...,1) Collect and preprocess relevant data; 2) de...,Implement a lightweight detection or predictio...,PlantVillage,CNN,"Python, XGBoost","crop disease detection, AI, Machine Learning, ...",SYNTHETIC
1,SYN-0002,2026-27,MCA,UG Mini Project,Ongoing,Healthcare & Medical Informatics,Web-Based Network Intrusion Detection Using Ra...,This project proposes a ug mini project soluti...,Existing approaches to network intrusion detec...,1) Collect and preprocess relevant data; 2) de...,"Build a web-based prototype, integrate a machi...",CIC-IDS2017,Random Forest,"Python, TensorFlow","network intrusion, AI, network intrusion detec...",SYNTHETIC
2,SYN-0003,2025-26,MCA,UG Mini Project,Completed,Cybersecurity,Web-Based Phishing Website Detection Using Ran...,This project proposes a ug mini project soluti...,Existing approaches to phishing website detect...,1) Collect and preprocess relevant data; 2) de...,"Develop a prototype, preprocess the dataset, e...",Kaggle phishing dataset,Random Forest,"Python, Wazuh","AI, Machine Learning, Random Forest, phishing",SYNTHETIC

In [4]:
display(pairs.head(5))

,pair_id,project_A_id,project_B_id,same_semantic_family,baseline_lexical_overlap_proxy,expert_similarity_label,similarity_category,annotation_note
0,PAIR-0001,SYN-0033,SYN-0119,0,0.7778,0,Not Similar,SYNTHETIC BENCHMARK LABEL — must be replaced/v...
1,PAIR-0002,SYN-0368,SYN-0009,0,0.6512,0,Not Similar,SYNTHETIC BENCHMARK LABEL — must be replaced/v...
2,PAIR-0003,SYN-0309,SYN-0337,0,0.7368,0,Not Similar,SYNTHETIC BENCHMARK LABEL — must be replaced/v...
3,PAIR-0004,SYN-0510,SYN-0295,0,0.7250,0,Not Similar,SYNTHETIC BENCHMARK LABEL — must be replaced/v...
4,PAIR-0005,SYN-0356,SYN-0485,1,0.8889,3,Highly Similar,SYNTHETIC BENCHMARK LABEL — must be replaced/v...

In [5]:
print(projects.isnull().sum())

project_id              0
academic_year           0
department              0
program_level           0
project_status          0
domain                  0
project_title           0
abstract                0
problem_statement       0
objectives              0
proposed_methodology    0
dataset                 0
algorithm_model         0
technology_tools        0
keywords                0
data_source             0
dtype: int64

In [6]:
print(pairs.isnull().sum())

pair_id                           0
project_A_id                      0
project_B_id                      0
same_semantic_family              0
baseline_lexical_overlap_proxy    0
expert_similarity_label           0
similarity_category               0
annotation_note                   0
dtype: int64

In [7]:
for column in pairs.columns:
    print("\n", "=" * 50)
    print(column)
    print(pairs[column].value_counts().head(20))

 ==================================================
pair_id
pair_id
PAIR-0001    1
PAIR-0002    1
PAIR-0003    1
PAIR-0004    1
PAIR-0005    1
PAIR-0006    1
PAIR-0007    1
PAIR-0008    1
PAIR-0009    1
PAIR-0010    1
PAIR-0011    1
PAIR-0012    1
PAIR-0013    1
PAIR-0014    1
PAIR-0015    1
PAIR-0016    1
PAIR-0017    1
PAIR-0018    1
PAIR-0019    1
PAIR-0020    1
Name: count, dtype: int64

 ==================================================
project_A_id
project_A_id
SYN-0051    15
SYN-0027    13
SYN-0062    13
SYN-0036    13
SYN-0243    13
SYN-0103    13
SYN-0144    13
SYN-0121    13
SYN-0013    12
SYN-0216    12
SYN-0206    12
SYN-0166    11
SYN-0041    11
SYN-0311    11
SYN-0088    11
SYN-0131    11
SYN-0270    11
SYN-0025    11
SYN-0201    11
SYN-0033    10
Name: count, dtype: int64

 ==================================================
project_B_id
project_B_id
SYN-0521    16
SYN-0581    16
SYN-0595    16
SYN-0580    15
SYN-0528    14
SYN-0585    14
SYN-0493    13
SYN-0450    13
SYN-0295    12
SYN-0424    12
SYN-0499    12
SYN-0466    12
SYN-0517    12
SYN-0451    12
SYN-0488    12
SYN-0560    11
SYN-0543    11
SYN-0470    11
SYN-0582    11
SYN-0557    11
Name: count, dtype: int64

 ==================================================
same_semantic_family
same_semantic_family
0    1500
1    1500
Name: count, dtype: int64

 ==================================================
baseline_lexical_overlap_proxy
baseline_lexical_overlap_proxy
0.9429    471
0.7000    268
0.7179    250
0.9412    213
0.7368    178
0.7632    174
0.9167    145
0.7568    128
0.7436    121
0.9394    115
1.0000     87
0.9143     85
0.6829     84
0.9706     78
0.7838     63
0.8056     41
0.7778     40
0.8108     38
0.9118     35
0.6667     32
Name: count, dtype: int64

 ==================================================
expert_similarity_label
expert_similarity_label
0    1336
3     581
2     514
1     334
4     235
Name: count, dtype: int64

 ==================================================
similarity_category
similarity_category
Not Similar           1336
Highly Similar         581
Moderately Similar     514
Slightly Similar       334
Nearly Duplicate       235
Name: count, dtype: int64

 ==================================================
annotation_note
annotation_note
SYNTHETIC BENCHMARK LABEL — must be replaced/validated by faculty annotation before publication.    3000
Name: count, dtype: int64

In [8]:
print(projects.columns.tolist())

['project_id', 'academic_year', 'department', 'program_level', 'project_status', 'domain', 'project_title', 'abstract', 'problem_statement', 'objectives', 'proposed_methodology', 'dataset', 'algorithm_model', 'technology_tools', 'keywords', 'data_source']

In [9]:
display(projects[
    [
        "project_id",
        "project_title",
        "abstract",
        "problem_statement",
        "objectives",
        "proposed_methodology",
        "dataset",
        "algorithm_model",
        "technology_tools"
    ]
].head(3))

,project_id,project_title,abstract,problem_statement,objectives,proposed_methodology,dataset,algorithm_model,technology_tools
0,SYN-0001,Prototype Crop Disease Detection Using CNN,This project proposes a ug mini project soluti...,Existing approaches to crop disease detection ...,1) Collect and preprocess relevant data; 2) de...,Implement a lightweight detection or predictio...,PlantVillage,CNN,"Python, XGBoost"
1,SYN-0002,Web-Based Network Intrusion Detection Using Ra...,This project proposes a ug mini project soluti...,Existing approaches to network intrusion detec...,1) Collect and preprocess relevant data; 2) de...,"Build a web-based prototype, integrate a machi...",CIC-IDS2017,Random Forest,"Python, TensorFlow"
2,SYN-0003,Web-Based Phishing Website Detection Using Ran...,This project proposes a ug mini project soluti...,Existing approaches to phishing website detect...,1) Collect and preprocess relevant data; 2) de...,"Develop a prototype, preprocess the dataset, e...",Kaggle phishing dataset,Random Forest,"Python, Wazuh"

In [10]:
print("Number of projects:", len(projects))

print(
    "Unique project IDs:",
    projects["project_id"].nunique()
)

print(
    "Pairs:",
    len(pairs)
)

Number of projects: 600
Unique project IDs: 600
Pairs: 3000

In [11]:
missing_A = ~pairs["project_A_id"].isin(projects["project_id"])
missing_B = ~pairs["project_B_id"].isin(projects["project_id"])

print("Missing Project A IDs:", missing_A.sum())
print("Missing Project B IDs:", missing_B.sum())

Missing Project A IDs: 0
Missing Project B IDs: 0

In [12]:
print("Unique A projects:", pairs["project_A_id"].nunique())
print("Unique B projects:", pairs["project_B_id"].nunique())

Unique A projects: 586
Unique B projects: 593

In [13]:
print(
    pairs.groupby("expert_similarity_label")[
        ["same_semantic_family"]
    ].mean()
)

                         same_semantic_family
expert_similarity_label
0                                    0.000000
1                                    0.508982
2                                    1.000000
3                                    1.000000
4                                    1.000000

In [14]:
print(
    pd.crosstab(
        pairs["same_semantic_family"],
        pairs["expert_similarity_label"],
        normalize="index"
    )
)

expert_similarity_label         0         1         2         3         4
same_semantic_family
0                        0.890667  0.109333  0.000000  0.000000  0.000000
1                        0.000000  0.113333  0.342667  0.387333  0.156667